/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { getCanonicalNonVisualSuiteInstructions, getFinalQualityGateInstructions, getManualCoverageInstructions } from './final-quality-gates.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'superpowers-apply-change',
    description: 'Implement tasks from an Superpowers change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an Superpowers change.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`superpowers list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/sp:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   superpowers status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   superpowers instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - Context file paths (varies by schema - for spec-driven this includes proposal, specs, design, tasks, execution-plan, and test-plan when present)
   - Attachment file paths in \`attachmentFiles\` when completed artifacts explicitly reference supported files under \`attachments/\`
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state
   - For spec-driven changes, \`tasks.md\` is the detailed progress checklist, \`execution-plan.md\` contains dispatch-unit coordination plus Step 1–5 execution guidance for each detailed task and final validation, and \`test-plan.md\` is the coverage draft plus Test Hardening record.

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using superpowers-continue-change
   - If \`state: "all_done"\`: read \`test-plan.md\` when present, confirm every concrete Test Hardening row outside \`## Final Quality Gates\` is complete **and** that the \`## Final Quality Gates\` record contains fresh integrated outcomes for every gate (each applicable gate passed; every \`not applicable\` result is justified). If the record is missing, failed, or applicable-blocked, run or resume final quality gates instead of suggesting archive.
   - Otherwise: proceed to implementation

4. **Read context files**

   Read the files listed in \`contextFiles\` from the apply instructions output.
   Read or inspect files listed in \`attachmentFiles\` when present. Treat the artifacts in \`contextFiles\` as the source of normative meaning for each attachment.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks, execution-plan, test-plan
   - Other schemas: follow the contextFiles from CLI output
   - When \`execution-plan.md\` contains \`Implementation Notes\`, read them as non-normative context for the relevant task. They preserve findings and reasoning, but do not define progress or completion.

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

6. **Implement tasks (loop until done or blocked)**
  
   In most cases, test-driven development should be used. Please refer to the \`test-driven-development\` skill.

   For each pending task:
   - Show which task is being worked on
   - Follow the task's planned Step 1–5 sequence and append concise \`Implementation Notes\` after a step when it produces a useful finding, reasoning point, viewpoint / trade-off, or summary / takeaway. Notes are narrative context, not status fields or a second checklist.
   - Mark task complete in the tasks file: \`- [ ]\` → \`- [x]\`
   - Continue to next task
   - Do not stop after a fixed batch size unless a blocker, ambiguity, or user interruption appears.
   - Keep switching directly to the next pending task so the run stays continuous.

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

7. **Run Test Hardening after implementation tasks are complete**

   For spec-driven changes with \`test-plan.md\`:
   - Task completion transitions into Test Hardening; it is not apply completion by itself.
   - Read \`test-plan.md\` and treat Test Hardening as complete only when every concrete testing/hardening status row outside \`## Final Quality Gates\` is complete. Final-gate rows are evaluated separately only after Test Hardening.
   - Use complete statuses such as \`covered\`, \`passed\`, or \`not applicable\`; \`planned\`, \`failing\`, blank, or placeholder rows keep hardening incomplete.
   - Distinguish worker-level verification in detailed \`tasks.md\` from post-integration Test Hardening in \`test-plan.md\`; passing worker-level tests is necessary but not sufficient for final apply completion.
   - Analyze which earlier tests were insufficient or not broad enough, then decide which supplemental tests are needed.
   - Add feasible missing tests for boundary cases, abnormal/error cases, non-critical paths, empty/missing/invalid states, permission/ownership failures, repeated actions, integration points, E2E flows, and cross-platform path behavior where relevant.
   - Record which tests this stage added or strengthened and any justified deferrals in \`test-plan.md\`.
   - Failing hardening tests or unresolved product defects block apply completion; fix them and rerun verification, or pause as blocked with the failing command, failure summary, affected files, and recommended next action.
   - Mark the relevant table rows complete only after evidence exists and no hardening failures or unresolved defects remain.

${getCanonicalNonVisualSuiteInstructions('Test Hardening')}

${getManualCoverageInstructions('Test Hardening')}

8. **Run final quality gates**

${getFinalQualityGateInstructions()}

9. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - Test Hardening status separately from implementation progress
   - If all tasks, Test Hardening, and every applicable final quality gate are done: show the four-gate outcome/evidence summary below, then suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓
**Test Hardening:** complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

### Test Hardening Summary
- Earlier test gaps: <summary>
- Tests added/strengthened: <summary>
- Verification: <selected checks and outcomes>
- Deferrals: <none or documented reasons>

### Final Quality Gates
| Gate | Outcome | Fresh worker evidence |
| --- | --- | --- |
| code review | passed / failed / blocked / not applicable | <worker report and findings resolution> |
| \`/sp:simplify\` | passed / failed / blocked / not applicable | <worker report and cleanup/skip summary> |
| \`/sp:verify\` | passed / failed / blocked / not applicable | <worker report, canonical suite, E2E disposition> |
| \`/sp:design-verify\` | passed / failed / blocked / not applicable | <worker report, UI/DESIGN.md disposition> |

Implementation, Test Hardening, and every applicable final quality gate are complete. You can archive this change with \`/sp:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Before claiming a task is completed, please refer to \`verification-before-completion\` skill
- Update task checkbox immediately after completing each task
- Treat execution-plan.md as implementation context and tasks.md as the progress-tracking checklist.
- Treat \`Implementation Notes\` in execution-plan.md as non-normative narrative context. Read them when resuming or reviewing a task, but never infer task status from them or use them instead of verification.
- Keep writes to shared execution-plan.md serialized when dispatch units run in parallel; workers may return notes to the coordinator for append after handoff.
- Treat completion independently: \`tasks.md\` completion means implementation tasks are done; \`test-plan.md\` testing/hardening table statuses outside \`## Final Quality Gates\` mean hardening is done.
- Treat Test Hardening as incomplete while any concrete testing/hardening status row outside \`## Final Quality Gates\` is \`planned\`, \`failing\`, blank, or still a placeholder.
- Analyze earlier testing gaps before checking hardening complete; ignore clearly unrelated changes and pause on ambiguous unrelated changes.
- Do not complete apply while hardening tests fail or product defects remain unresolved.
- Do not recommend archive while a final quality gate is failed or an applicable gate is blocked.
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles and attachmentFiles from CLI output, don't assume specific file names
- Never start implementation on main/master branch without explicit user consent
- Do not automatically repeat proposal review before starting. The normal \`/sp:propose\` path performs it after creating all required artifacts; users may invoke \`/sp:review <change>\` voluntarily.
- Keep the final integration review separate: after dispatch units integrate, review cross-unit behavior, the integrated diff, code quality, and full validation before completion.
- Keep the task loop continuous by default; only pause when blocked, unclear, or explicitly asked to stop

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly

`,
    license: 'MIT',
    compatibility: 'Requires superpowers CLI.',
    metadata: { author: 'superpowers', version: '1.0' },
  };
}

export function getSpApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'SP: Apply',
    description: 'Implement tasks from an Superpowers change',
    category: 'Workflow',
    tags: ['workflow', 'artifacts'],
    content: `Implement tasks from an Superpowers change.

**Input**: Optionally specify a change name (e.g., \`/sp:apply add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`superpowers list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/sp:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   superpowers status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   superpowers instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - Context file paths (varies by schema)
   - Attachment file paths in \`attachmentFiles\` when completed artifacts explicitly reference supported files under \`attachments/\`
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using \`/sp:continue\`
   - If \`state: "all_done"\`: read \`test-plan.md\` when present, confirm every concrete Test Hardening row outside \`## Final Quality Gates\` is complete **and** that the \`## Final Quality Gates\` record contains fresh integrated outcomes for every gate (each applicable gate passed; every \`not applicable\` result is justified). If the record is missing, failed, or applicable-blocked, run or resume final quality gates instead of suggesting archive.
   - Otherwise: proceed to implementation

4. **Read context files**

   Read the files listed in \`contextFiles\` from the apply instructions output.
   Read or inspect files listed in \`attachmentFiles\` when present. Treat the artifacts in \`contextFiles\` as the source of normative meaning for each attachment.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks, execution-plan, test-plan
   - Other schemas: follow the contextFiles from CLI output
   - When \`execution-plan.md\` contains \`Implementation Notes\`, read them as non-normative context for the relevant task. They preserve findings and reasoning, but do not define progress or completion.

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

6. **Implement tasks (loop until done or blocked)**

   For each pending task:
   - Show which task is being worked on
   - Make the code changes required
   - Keep changes minimal and focused
   - Follow the task's planned Step 1–5 sequence and append concise \`Implementation Notes\` after a step when it produces a useful finding, reasoning point, viewpoint / trade-off, or summary / takeaway. Notes are narrative context, not status fields or a second checklist.
   - Mark task complete in the tasks file: \`- [ ]\` → \`- [x]\`
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

7. **Run Test Hardening after implementation tasks are complete**

   For spec-driven changes with \`test-plan.md\`:
   - Task completion transitions into Test Hardening; it is not apply completion by itself.
   - Read \`test-plan.md\` and treat Test Hardening as complete only when every concrete testing/hardening status row outside \`## Final Quality Gates\` is complete. Final-gate rows are evaluated separately only after Test Hardening.
   - Use complete statuses such as \`covered\`, \`passed\`, or \`not applicable\`; \`planned\`, \`failing\`, blank, or placeholder rows keep hardening incomplete.
   - Distinguish worker-level verification in detailed \`tasks.md\` from post-integration Test Hardening in \`test-plan.md\`; passing worker-level tests is necessary but not sufficient for final apply completion.
   - Analyze which earlier tests were insufficient or not broad enough, then decide which supplemental tests are needed.
   - Add feasible missing tests for boundary cases, abnormal/error cases, non-critical paths, empty/missing/invalid states, permission/ownership failures, repeated actions, integration points, E2E flows, and cross-platform path behavior where relevant.
   - Record which tests this stage added or strengthened and any justified deferrals in \`test-plan.md\`.
   - Failing hardening tests or unresolved product defects block apply completion; fix them and rerun verification, or pause as blocked with the failing command, failure summary, affected files, and recommended next action.
   - Mark the relevant table rows complete only after evidence exists and no hardening failures or unresolved defects remain.

${getCanonicalNonVisualSuiteInstructions('Test Hardening')}

${getManualCoverageInstructions('Test Hardening')}

8. **Run final quality gates**

${getFinalQualityGateInstructions()}

9. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - Test Hardening status separately from implementation progress
   - If all tasks, Test Hardening, and every applicable final quality gate are done: show the four-gate outcome/evidence summary below, then suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓
**Test Hardening:** complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

### Test Hardening Summary
- Earlier test gaps: <summary>
- Tests added/strengthened: <summary>
- Verification: <selected checks and outcomes>
- Deferrals: <none or documented reasons>

### Final Quality Gates
| Gate | Outcome | Fresh worker evidence |
| --- | --- | --- |
| code review | passed / failed / blocked / not applicable | <worker report and findings resolution> |
| \`/sp:simplify\` | passed / failed / blocked / not applicable | <worker report and cleanup/skip summary> |
| \`/sp:verify\` | passed / failed / blocked / not applicable | <worker report, canonical suite, E2E disposition> |
| \`/sp:design-verify\` | passed / failed / blocked / not applicable | <worker report, UI/DESIGN.md disposition> |

Implementation, Test Hardening, and every applicable final quality gate are complete. You can archive this change with \`/sp:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Treat execution-plan.md as implementation context and tasks.md as the progress-tracking checklist.
- Treat \`Implementation Notes\` in execution-plan.md as non-normative narrative context. Read them when resuming or reviewing a task, but never infer task status from them or use them instead of verification.
- Keep writes to shared execution-plan.md serialized when dispatch units run in parallel; workers may return notes to the coordinator for append after handoff.
- Treat \`tasks.md\` completion as the transition into Test Hardening when \`test-plan.md\` exists.
- Treat Test Hardening as incomplete while any concrete testing/hardening status row outside \`## Final Quality Gates\` is \`planned\`, \`failing\`, blank, or still a placeholder.
- Analyze earlier testing gaps before checking hardening complete; ignore clearly unrelated changes and pause on ambiguous unrelated changes.
- Do not complete apply while hardening tests fail or product defects remain unresolved.
- Do not recommend archive while a final quality gate is failed or an applicable gate is blocked.
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles and attachmentFiles from CLI output, don't assume specific file names
- Do not automatically repeat proposal review before starting. The normal \`/sp:propose\` path performs it after creating all required artifacts; users may invoke \`/sp:review <change>\` voluntarily.
- Keep the final integration review separate: after dispatch units integrate, review cross-unit behavior, the integrated diff, code quality, and full validation before completion.

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`
  };
}
