/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { getCanonicalNonVisualSuiteInstructions, getManualCoverageInstructions } from './final-quality-gates.js';

const finalQualityRetryInstructions = `### Final-quality Verify retries:
   - When Verify is delegated by \`/sp:apply\`, label the report \`Verify round 1\` through \`Verify round 4\`. The first attempt after Simplify is round 1; every attempt, including a retry, uses a fresh subagent.
   - Every round reruns this complete canonical non-visual preflight before requirement/scenario assessment and applicable Manual Coverage. Preserve separate command and Manual Coverage evidence for every numbered round.
   - Treat \`CRITICAL\` as \`P0\` for final-quality retry decisions. Before round four, the worker reports each resolvable failed check, applicable Manual Coverage failure, or P0/CRITICAL finding. When the coordinator repairs an accepted failure or CRITICAL finding, retry from Verify with a fresh worker. Do not restart code review or Simplify solely for this retry.
   - A missing runtime, credential, browser capability, dependency, or other prerequisite is \`BLOCKER\`: report \`blocked\`, name it, pause immediately, and do not consume a round. If round four still has a failed check, applicable Manual Coverage failure, or P0/CRITICAL finding, report \`failed\`; do not begin a fifth round or recommend archive.`;

const verifyCompletenessSteps = `4. **Verify Completeness**

   **Task Completion**:
   - If tasks.md exists in contextFiles, read it
   - Review each task individually for actual completion; do not rely on checkbox state alone — \`- [x]\` does not prove the work is done. Judge completion from evidence in the actual code implementation.
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`superpowers/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
       - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"
     - For each scenario in delta specs (marked with "#### Scenario:"):
       - Check if conditions are handled in code
       - Check if tests exist covering the scenario
       - If scenario appears uncovered:
         - Add WARNING: "Scenario not covered: <scenario name>"
         - Recommendation: "Add test or implementation for scenario: <description>"

   **Test Coverage**:
   - Read and follow the \`full-qa-test\` skill. If it is unavailable, use the closest test-coverage skill in the environment.
   - Treat \`design.md\`, delta specs, \`test-plan.md\`, and the current implementation as the input set. Assess whether \`test-plan.md\` still adequately covers the change:
     - Map requirements, scenarios, design decisions, and identified risk paths to concrete rows or matrix entries in \`test-plan.md\`.
     - Find missing coverage: spec or implementation scope with no corresponding automated, manual, or justified deferred row.
     - Find stale coverage: rows that no longer match the implementation, were superseded by code changes, or describe tests that should be updated or removed.
     - Find shallow coverage: happy-path-only rows where delta specs or design call for boundaries, errors, permissions, state transitions, or integration paths.
   - When using \`full-qa-test\`, use its dimensions as a gap-analysis lens. During Verify, assess the plan and existing tests; do not claim full six-dimensional execution unless the active skill phase requires it.
   - When gaps, stale rows, or unjustified deferrals are found:
     - Add WARNING: "Test plan gap: <details>"
     - Recommendation: "Add or update test-plan.md for <requirement/scenario/risk>; cite the missing case or dimension"
   - The Verify worker reports findings by default; do not edit \`test-plan.md\` unless the host workflow explicitly authorizes repair.`;

const repairOwnershipInstructions = `**Repair ownership**

- The Verify worker is read-only by default. Report findings and evidence before any implementation changes; include severity, affected files or journeys, reproduction details, and a specific recommendation.
- The coordinator evaluates and repairs accepted product, architecture, or workflow findings, then runs targeted verification. A host-native workflow may authorize worker self-repair only when that authorization is explicit.
- If a finding cannot be reproduced or its required repair is ambiguous, investigate or clarify before editing. Do not modify the implementation merely to make the report appear clean.
- In final-quality Verify, a repair ends the current worker's result. The coordinator starts the next required fresh Verify round; the reporting worker does not silently approve its own repair.`;

const verifyCorrectnessAndReportTail = `5. **Verify Correctness**

${getCanonicalNonVisualSuiteInstructions('verify')}

${getManualCoverageInstructions('verify')}

6. **Verify Coherence**

   **Design Adherence**:
   - If design.md exists in contextFiles:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

7. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Manual Coverage | M/N rows, methods, evidence |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Test plan gaps or stale test rows
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If any applicable Manual Coverage row is \`blocked\` or \`failed\`: "Verify blocked/failed: resolve the Manual Coverage outcome before archiving." Do not report Correctness as passed.
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

## Other Rules

${finalQualityRetryInstructions}

### Verification Heuristics

- **Completeness**: Focus on objective checklist items (tasks, requirements, scenarios) and test-plan gap analysis against design, specs, and implementation
- **Correctness**: Run the canonical test suite and Manual Coverage (including \`programmatic-browser\` / \`agent-browser\` methods); use inspectable evidence rather than inference alone
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

${repairOwnershipInstructions}

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

## Output Format

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- When running as an apply final-quality gate: \`Verify round: <1-4>\`, \`Fresh worker: <identity>\`, retry disposition, canonical preflight/Manual Coverage evidence for that round, and the terminal \`failed\` or \`blocked\` reason where applicable
- Repair ownership: findings reported without edits by default; coordinator remediation and targeted-validation evidence when applicable
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`;

const verifyReportStructure = `3. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks, spec coverage, scenario mapping, and test-plan coverage
   - **Correctness**: Track test-suite preflight and Manual Coverage (including browser methods)
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

${verifyCompletenessSteps}

${verifyCorrectnessAndReportTail}`;

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'superpowers-verify-change',
    description: 'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

## Steps

1. **If no change name provided, prompt for selection**

   Run \`superpowers list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status and load artifacts**

   \`\`\`bash
   superpowers status --change "<name>" --json
   \`\`\`

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

   \`\`\`bash
   superpowers instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory, context files, and attachment files. Read all available artifacts from \`contextFiles\`, and read or inspect files from \`attachmentFiles\` when present. Treat artifacts as the source of normative meaning for each attachment.

${verifyReportStructure}`,
    license: 'MIT',
    compatibility: 'Requires superpowers CLI.',
    metadata: { author: 'superpowers', version: '1.0' },
  };
}

export function getSpVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'SP: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify'],
    content: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name after \`/sp:verify\` (e.g., \`/sp:verify add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

## Steps

1. **If no change name provided, prompt for selection**

   Run \`superpowers list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status and load artifacts**

   \`\`\`bash
   superpowers status --change "<name>" --json
   \`\`\`

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

   \`\`\`bash
   superpowers instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory, context files, and attachment files. Read all available artifacts from \`contextFiles\`, and read or inspect files from \`attachmentFiles\` when present. Treat artifacts as the source of normative meaning for each attachment.

${verifyReportStructure}`
  };
}
